server:
  port: 8000

db:
  type: 'postgres'
  port: 5432
  database: task_management
  synchronize: false

jwt:
  secret: 'topSecret51'
  expiresIn: 3600

PRISMA_ENDPOINT: http://localhost:4466
PRISMA_SECRET: pi389xjam2b3pjsd0
JWT_SECRET: 23oijdsm23809sdf
